version: "3.8"

services:
  app:
    build: .
    container_name: my-app
    restart: always
    expose:
      - "5000"  # internal port for NGINX to connect

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "8080:80"  # host 8080 -> container 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
