version: "3.8"

services:
  app:
    build: .
    container_name: my-app
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest   # ✅ USE REAL NGINX IMAGE
    container_name: my-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
