name: Docker Compose CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop old containers
        run: docker-compose down || true

      - name: Build and Start Containers
        run: docker-compose up -d --build

      - name: Wait for App
        run: sleep 10

      - name: Test Application
        run: |
          curl -f http://localhost || exit 1
