name: project for pythine
on: 
  push:
    branches: [main]
job:
  build:
    runs-on: [self-hosted, oracle-vm, linux, arm64]
    steps:
      - uses: action/checkout@v3

      - name: build docker image
        run: docker build -t project-1:latest .
      - name: Run Container
        run: |
          docker run -d -p 5000:5000 --name project1 project1:latest 
          sleep 2

      - name: test App
           run: |
             curl http://localhost:5000
             curl http://localhost:5000/health
             
      - name: Cleanup
        run: docker stop project1 && docker rm project1

